name: Build Subject

on:
  # schedule:
  #   # Run “At 02:00 on day-of-month 1 in every 3rd month.”  (see https://crontab.guru)
  #   - cron: '0 2 1 */3 *'
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ^6.32.2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build Subject
        run: pnpm ids
        run: pnpm subject
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-commit build subject